### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by krisbros** [patrickmoffitt/Adafruit-Feather-M0-Motion-Camera#4]
Hello, 
The Schematic drawing does not seems to be right compared with the description text. 

- Transistor go to channel A1 on the Feather.  
- PIR sensor output go to A0. 

Some bacic question;
- The camera comes with a resistor, but why is this placed in the PIR sensor output? 
- Can you describe the funktion of the transistor coupled in GND with the camera and the PIR.

Thanks again for the project. 

Regards 
Kristian

**Comment by patrickmoffitt** [comment]
Hi @krisbros,

Thanks for pointing out that documentation error on the schematic and on the README.md. Both have now been corrected.

The camera comes with two resistors for making a resistor divider in the case where the camera is used on a micro-controller with 5V logic. See [this tutorial](https://learn.adafruit.com/ttl-serial-camera/using-commtool) for further details. The Feather M0 has 3.3V logic and so these were not needed in this project.

I apologize for the way the [PN2907A](https://cdn-shop.adafruit.com/product-files/3598/PN2907A-D.PDF) transistor was previously shown on the schematic. The version you were looking at lacked a wire-hop and gave the appearance that GND and 5V were connected between the PIR and CAMERA headers. This has since been corrected. Thank you for your question which brought the error to my attention.

As to how the transistor works; it basically works like a double-pole single-throw switch. It has 3 pins. The bottom one is pin 1 (the emitter). The left one is pin 2 (the base). The top one is pin 3 (the collector). The base pin (2) controls the flow of current between the emitter (1) and collector (3). In his type of transistor [(PNP)](https://learn.sparkfun.com/tutorials/transistors/all) current flows from the the emitter to the collector when the base is pulled low. In my circuit this has the effect of connecting the camera's ground pin to ground and allowing current to flow through the camera to ground. This use of transistors is called switching the current sink. Here is [another tutorial](https://www.petervis.com/GCSE_Design_and_Technology_Electronic_Products/Transistor_as_a_Switch/Transistor_as_a_Switch.html) you may find helpful to understanding transistors. When the base is pulled high the flow of current stops. In my circuit this shuts off the camera (to save power).

Cheers,
Patrick Moffitt

**Comment by krisbros** [comment]
Hello Patrick,
Thanks alot! Will be working with this project for a while. It will be interesting to see if I manage to solve the programming i C++. That is the main focus now. I use the feather adalogger in my project. I have also thought about develop some new funktions, but first solve the things I already have started.  

Regards 
Kristian
